name: release-build

on:
  push:
    tags:
      - 'acra-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Checkout acra
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Publish
        run: ./gradlew publish --no-daemon
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASSWORD: ${{ secrets.BINTRAY_PASSWORD }}
